/*
 * IHM.java
 *
 * Created on 11 oct. 2011, 00:54:35
 */
package ihm;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

import testeur.TestKhiDeux;
import generateur.Classe;
import generateur.Generateur;
import generateur.GenerateurUniforme;

/**
 *
 * @author Kévin
 */
public class IHM extends javax.swing.JFrame {
	
	javax.swing.JLabel[]  tabLabel = new javax.swing.JLabel[10];

    /** Creates new form IHM */
    public IHM() {
        initComponents();
        
        // creation d'un tableau pour les labels des classes
        tabLabel[0] = labelClasse1;
        tabLabel[1] = labelClasse2;
        tabLabel[2] = labelClasse3;
        tabLabel[3] = labelClasse4;
        tabLabel[4] = labelClasse5;
        tabLabel[5] = labelClasse6;
        tabLabel[6] = labelClasse7;
        tabLabel[7] = labelClasse8;
        tabLabel[8] = labelClasse9;
        tabLabel[9] = labelClasse10;
        		
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelGraphique = new javax.swing.JPanel();
        boutonUniforme = new javax.swing.JButton();
        textFieldEchantillon = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        boutonNormale = new javax.swing.JButton();
        boutonExponentielle = new javax.swing.JButton();
        boutonPoisson = new javax.swing.JButton();
        boutonWeibull = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelClasse3 = new javax.swing.JLabel();
        labelClasse8 = new javax.swing.JLabel();
        labelClasse1 = new javax.swing.JLabel();
        labelClasse6 = new javax.swing.JLabel();
        labelClasse2 = new javax.swing.JLabel();
        labelClasse7 = new javax.swing.JLabel();
        labelClasse10 = new javax.swing.JLabel();
        labelClasse9 = new javax.swing.JLabel();
        labelClasse5 = new javax.swing.JLabel();
        labelClasse4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Géneration de nombres aléatoires");

        panelGraphique.setBackground(new java.awt.Color(255, 255, 255));
        panelGraphique.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelGraphiqueLayout = new javax.swing.GroupLayout(panelGraphique);
        panelGraphique.setLayout(panelGraphiqueLayout);
        panelGraphiqueLayout.setHorizontalGroup(
            panelGraphiqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );
        panelGraphiqueLayout.setVerticalGroup(
            panelGraphiqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        boutonUniforme.setText("Loi Uniforme");
        boutonUniforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonUniformeActionPerformed(evt);
            }
        });

        jLabel1.setText("Taille de l'échantillon à générer:");

        boutonNormale.setText("Loi Normale");
        boutonNormale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonNormaleActionPerformed(evt);
            }
        });

        boutonExponentielle.setText("Loi Exponentielle");
        boutonExponentielle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonExponentielleActionPerformed(evt);
            }
        });

        boutonPoisson.setText("Loi de Poisson");
        boutonPoisson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonPoissonActionPerformed(evt);
            }
        });

        boutonWeibull.setText("Loi de Weibull");
        boutonWeibull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonWeibullActionPerformed(evt);
            }
        });

        jLabel2.setText("Classe 1:");

        jLabel3.setText("Classe 2:");

        jLabel4.setText("Classe 3:");

        jLabel5.setText("Classe 4:");

        jLabel6.setText("Classe 5:");

        jLabel7.setText("Classe 8:");

        jLabel8.setText("Classe 6:");

        jLabel9.setText("Classe 7:");

        jLabel10.setText("Classe 10:");

        jLabel11.setText("Classe 9:");

        jLabel12.setText("Classement de l'échantillon par classes :");

        labelClasse3.setBackground(new java.awt.Color(255, 255, 255));
        labelClasse3.setText("                    ");

        labelClasse8.setBackground(new java.awt.Color(255, 255, 255));
        labelClasse8.setText("                    ");

        labelClasse1.setBackground(new java.awt.Color(255, 255, 255));
        labelClasse1.setText("                    ");

        labelClasse6.setBackground(new java.awt.Color(255, 255, 255));
        labelClasse6.setText("                    ");

        labelClasse2.setBackground(new java.awt.Color(255, 255, 255));
        labelClasse2.setText("                    ");

        labelClasse7.setBackground(new java.awt.Color(255, 255, 255));
        labelClasse7.setText("                    ");

        labelClasse10.setBackground(new java.awt.Color(255, 255, 255));
        labelClasse10.setText("                    ");

        labelClasse9.setBackground(new java.awt.Color(255, 255, 255));
        labelClasse9.setText("                    ");

        labelClasse5.setBackground(new java.awt.Color(255, 255, 255));
        labelClasse5.setText("                    ");

        labelClasse4.setBackground(new java.awt.Color(255, 255, 255));
        labelClasse4.setText("                    ");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("GRAPHIQUE");

        jToolBar1.setRollover(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(boutonUniforme, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(boutonNormale, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(boutonWeibull, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(boutonPoisson, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(boutonExponentielle, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel4)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel6)))
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelClasse2)
                                                .addComponent(labelClasse4)
                                                .addComponent(labelClasse3)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(labelClasse9)
                                                    .addComponent(labelClasse8)
                                                    .addComponent(labelClasse7)
                                                    .addComponent(labelClasse6)
                                                    .addComponent(labelClasse10)
                                                    .addComponent(labelClasse5)))
                                            .addComponent(labelClasse1)))
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(10, 10, 10)
                        .addComponent(panelGraphique, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldEchantillon, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                        .addComponent(jLabel23)
                        .addGap(236, 236, 236))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textFieldEchantillon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGraphique, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel12)
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(boutonUniforme)
                                        .addGap(18, 18, 18)
                                        .addComponent(boutonNormale)
                                        .addGap(18, 18, 18)
                                        .addComponent(boutonExponentielle)
                                        .addGap(18, 18, 18)
                                        .addComponent(boutonPoisson)
                                        .addGap(18, 18, 18)
                                        .addComponent(boutonWeibull))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelClasse2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelClasse3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelClasse4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(labelClasse5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelClasse6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelClasse7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelClasse8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelClasse9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelClasse10))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel2)
                                                    .addComponent(labelClasse1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel10))))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>

private void boutonUniformeActionPerformed(java.awt.event.ActionEvent evt) {

	// generation des valeurs aléatoires
	GenerateurUniforme generateur = new GenerateurUniforme();
	generateur.generer(Integer.parseInt(this.textFieldEchantillon.getText()));
	
	// rangement des valeurs aléatoire dans les classes
	ArrayList<Classe> list = generateur.genererClasses();
	
	//affichage des classes
	for (int i=0; i<10; i++){
		tabLabel[i].setText(Integer.toString((int) list.get(i).getEffectifReel()));
	}
	
	// test du Khi²
	TestKhiDeux khi2 = new TestKhiDeux();
	khi2.test(generateur);
	
	genererGraphique(generateur, "Loi UNIFORME");
	
	
}

private void boutonNormaleActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

private void boutonExponentielleActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

private void boutonPoissonActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

private void boutonWeibullActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

private void genererGraphique(Generateur generateur, String name){
	XYSeries series = new XYSeries("XY Chart");
	series.add(0, 0);
	int valeur = 0;
	ArrayList<Classe> list = generateur.getListeClasses();
	for (int i=1; i<list.size()+1; i++){
		valeur += list.get(i-1).getEffectifReel();
		series.add(i,(double) valeur/generateur.getNbGenerations());
		
	}
	
	// Ajoute la série au dataset
	XYSeriesCollection dataset = new XYSeriesCollection();
	dataset.addSeries(series);
	
	// Genere le graphique
	JFreeChart chart = ChartFactory.createXYLineChart(
		name, 	  // Titre
		"x-axis", // Nom de l'axe X
		"y-axis", // Nom de l'axe Y
		dataset,  // Dataset
		PlotOrientation.VERTICAL, // Orientation
		true, // Affichage de la legende
		true, // Utilisation du tooltip
		false // pas de generation d'URL
	);
	
	try {
		ChartUtilities.saveChartAsJPEG(new File("D:\\chart.jpg"), chart, 496, 434);
	} catch (IOException e) {
		System.err.println("Problem occurred creating chart. "+e.getMessage());
	}
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new IHM().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton boutonExponentielle;
    private javax.swing.JButton boutonNormale;
    private javax.swing.JButton boutonPoisson;
    private javax.swing.JButton boutonUniforme;
    private javax.swing.JButton boutonWeibull;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labelClasse1;
    private javax.swing.JLabel labelClasse10;
    private javax.swing.JLabel labelClasse2;
    private javax.swing.JLabel labelClasse3;
    private javax.swing.JLabel labelClasse4;
    private javax.swing.JLabel labelClasse5;
    private javax.swing.JLabel labelClasse6;
    private javax.swing.JLabel labelClasse7;
    private javax.swing.JLabel labelClasse8;
    private javax.swing.JLabel labelClasse9;
    private javax.swing.JPanel panelGraphique;
    private javax.swing.JTextField textFieldEchantillon;
    // End of variables declaration
}
